# 数据库连接配置
spring:
  datasource:
    dynamic:
      primary: worker
      strict: false
      datasource:
        worker:
          url: jdbc:mysql://127.0.0.1:3306/worker?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&rewriteBatchedStatements=true
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            #连接池初始化大小
            initial-size: 5
            #连接池最小值
            min-idle: 5
            #连接池最大值
            max-active: 10
            #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
            max-wait: 60000
            #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
            time-between-eviction-runs-millis: 60000
            #配置一个连接在池中最小生存的时间
            min-evictable-idle-time-millis: 300000
  redis:
    host: 127.0.0.1
    port: 6379
